// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brnzacwkfhshvxnaprsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybnphY3drZmhzaHZ4bmFwcnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDYwNTUsImV4cCI6MjA2MDI4MjA1NX0.fikLvKmvFFt6H_hV8TDXxIKs58S7pdrjhpmJdON029I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);